preprocessing:
    experiment_name: tdifd
    path: wallpapers_small
    img_size:
      - 227
      - 227

vocabulary:

histograms:

tfidf:

comparisons:

html:
    path: ../resources/wallpapers_small_processed_227

deep_feature_extraction:
  experiment_name:  a
  outputlayer: 20
  path: ../resources/wallpapers_small_processed_227
  img_size:
    - 227
    - 227
  save_features: yes


